# Generated by Django 2.2.4 on 2019-09-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='focus_cities',
            field=models.TextField(default=[]),
        ),
        migrations.AddField(
            model_name='user',
            name='focus_stars',
            field=models.TextField(default=[]),
        ),
        migrations.AddField(
            model_name='user',
            name='focus_stock',
            field=models.TextField(default=[]),
        ),
    ]
