# Generated by Django 2.2.4 on 2019-09-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_auto_20190904_1325'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='authorizati_nicknam_b76290_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='authorizati_open_id_8675f5_idx',
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['open_id', 'nickname'], name='authorizati_open_id_5cfcc1_idx'),
        ),
    ]
